use_frameworks!

target 'RxFirebase_Example' do
  pod 'RxFirebase/Firestore', :path => '../'
  pod 'RxFirebase/Core', :path => '../'

  target 'RxFirebase_Tests' do
    inherit! :search_paths

    
  end
end

