use_frameworks!

target 'RxFirebase_Example' do
  pod 'RxFirebase/Firestore', :path => '../'
  pod 'RxFirebase/RemoteConfig', :path => '../'

  target 'RxFirebase_Tests' do
    inherit! :search_paths

    
  end
  
  pre_install do |installer|
      # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
      Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
  end
end

